import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "../NavBar";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import "@radix-ui/themes/styles.css";
const inter = Inter({ subsets: ["latin"] });
import { Theme } from "@radix-ui/themes";
export const metadata: Metadata = {
  title: "Bent Oak Test",
  description: "Generated by Sasan Salehzadeh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <ReactQueryProvider>
            <NavBar />
            <main>{children}</main>
          </ReactQueryProvider>
        </Theme>
      </body>
    </html>
  );
}
